services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    init: true
    env_file:
      - .env
    environment:
      NODE_ENV: development # for now, until I have good prod logging
    volumes:
      - db-data:/home/node/app/prisma/db
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 -O- http://bot:${HEALTHCHECK_PORT}/healthcheck || exit 1" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s

volumes:
  db-data:
